---
title: "Untitled"
author: "Tarini Bhatnagar"
date: "4/11/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE}
library(httr)
library(installr)
library(stringr)
library(ggplot2)
library(ggmap)
```

```{r}

#Wrapper function
get_weather <- function(city_name,continent){
  
  # Computes the minimum, maximum temperature, wind direction & speed forecast for next 5 days
  # Input: city_name: (String)name of a city
  # Input: continent: (String )continent corresponding to city_name
  
  #Error handling
  if (!is.character(city_name))
        stop("Need to input an string.")
  if (!is.character(continent))
        stop("Need to input an string.")
  if (!(continent %in% c("Asia","Africa","Australasia","Europe","North America","South America")))
        stop("Continent can only be one of Asia, Africa, Australasia, Europe, North America, South America ")
  
  #Base query
  query_base <- "https://www.metaweather.com/api/"
  
  #Retrieve where on earth id  and coordinates of city through API
  search_location <- content(GET(paste0(query_base,"location/search/?query=",city_name)))
  woeid <- search_location[[1]]$woeid
  lat_long <- search_location[[1]]$latt_long
  
  #Plot location of city on Map
  
  #Get map to use as base map
  map <- get_map(location = continent, zoom = 3)
  coord <- str_split(lat_long,",")
  lat <- as.numeric(coord[[1]][1])
  lon <- as.numeric(coord[[1]][2])
  df <- as.data.frame(cbind(lon,lat))
  loc_map <- ggmap(map)+
    geom_point(data = df, aes(x = lon, y = lat), size = 3,fill="red", shape = 21)  
  print(loc_map)
  search_temp <- content(GET(paste0(query_base,"location/",woeid,"/")))
  
}

#Test examples
response <- get_weather("oslo","Europe")
#response <- get_weather("mumbai","Asia")
#response <- get_weather("denver","North America")
```


```{r}
#Base query
query_base <- "https://www.metaweather.com/api/"
  
#Retrieve where on earth id  and coordinates of city through API
search_location <- content(GET(paste0(query_base,"location/search/?query=","oslo")))
woeid <- search_location[[1]]$woeid
lat_long <- search_location[[1]]$latt_long
  
#Plot location of city on Map
  
#Get map to use as base map
#map <- get_map(location = continent, zoom = 3)
coord <- str_split(lat_long,",")
lat <- as.numeric(coord[[1]][1])
lon <- as.numeric(coord[[1]][2])
df <- as.data.frame(cbind(lon,lat))
#loc_map <- ggmap(map)+
  #geom_point(data = df, aes(x = lon, y = lat), size = 3,fill="red", shape = 21)  
#print(loc_map)
search_temp <- content(GET(paste0(query_base,"location/",woeid,"/")))
date <- search_temp[[1]][[1]]$applicable_date
min_temp <- as.numeric(search_temp[[1]][[1]]$min_temp)
max_temp <- as.numeric(search_temp[[1]][[1]]$max_temp)
ws_name <- search_temp[[1]][[1]]$weather_state_name
ws_abbr <- search_temp[[1]][[1]]$weather_state_abbr


library ("png")

#zoom <- 2
#map <- readPNG (sprintf ("mapquest-world-%i.png", zoom))
#map <- as.raster(apply(map, 2, rgb))
#
# cut map to what I really need
#pxymin <- LonLat2XY (-180,73,zoom+8)$Y # zoom + 8 gives pixels in the big map
#pxymax <- LonLat2XY (180,-60,zoom+8)$Y # this may or may not work with google
                                       # zoom values
#map <- map [pxymin : pxymax,]
map <- get_map(location = "world", zoom = 1)
loc_map <- ggmap(map)+
  geom_point(data = df, aes(x = lon, y = lat), size = 2,shape = 21, fill="red") +
  geom_text(data = df, aes(x = lon+2, y = lat+2, label=paste(ws_name)), fontface="bold", color="red", size=3)
print(loc_map)

```

